
services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./envs/db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: packages/db/migrate.Dockerfile
    env_file:
      - packages/db/.env
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma migrate deploy"

  api:
    build:
      context: .
      dockerfile: apps/api/api.Dockerfile
    container_name: net-api
    ports:
      - "8080:8080"
    depends_on:
      - migrate

  hub:
    build:
      context: .
      dockerfile: apps/hub/hub.Dockerfile
    container_name: hub-server
    ports:
      - "8081:8081"

    depends_on:
      - migrate

  validator:
    build:
      context: .
      dockerfile: apps/validator/validator.Dockerfile
    container_name: validator-node
    env_file:
      - ./envs/validator.env  
    depends_on:
      - hub

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile 
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./envs/frontend.env
    depends_on:
      - api

volumes:
  postgres-data:
